### ISSUE TITLE
Image URL not working 

### ISSUE THREAD

**Issue by miiosteam** [NGromann/SwiftHtmlPdf#6]
I have added image in HTML string but in PDF it's showing blank

**Comment by NGromann** [comment]
Hi @miiosteam,

Links to images that use an url do not work at the moment. For now you could either embed the images with Base64 like [here](https://stackoverflow.com/a/8499716/12277591) or as SVG like in the [example](https://github.com/NGromann/SwiftHtmlPdf/blob/f90d6dd4e9a6741b0d8000675241344d18724e35/Example/SwiftHtmlPdfExample/SwiftHtmlPdfExample/planbuildpro-baukosten-template.html#L78)
